name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses:actions/checkout@v2

    - name: Run Unit Tests
      run: dotnet test Tests/Xamarin.Bookshelf.Unit.Tests -v n

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: 'Functions/Xamarin.Bookshelf.Functions/'
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
      working-directory: 'Functions/Xamarin.Bookshelf.Functions/'
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: functions
        path: 'Functions/Xamarin.Bookshelf.Functions/bin/Release/netcoreapp3.1/publish'

  Up:
    name: Pulumi Update
    needs: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/download-artifact@v2
        with:
          name: functions
          path: './DEVOPS/Artifacts/Functions'

      - uses: docker://pulumi/actions
        with:
          args: up --yes
        env:          
          ARTIFACTS_WORKSPACE: '../Artifacts'
          PULUMI_ROOT: './DEVOPS/Xamarin.Bookshelf.Infrastructure'
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
